<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Yarp.ReverseProxy" />
    <InternalsVisibleTo Include="33pol.Proxy.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\33pol.Policy\33pol.Policy.csproj" />
    <ProjectReference Include="..\33pol.Registry\33pol.Registry.csproj" />
    <ProjectReference Include="..\33pol.Core\33pol.Core.csproj" />
  </ItemGroup>
</Project>
