#!/usr/bin/env bash
# =============================================================================
# 33pol-deploy.sh — versioned Docker Compose deploy & instant rollback for 33pol
#
# Builds an immutable, version-tagged gateway image, snapshots the database
# before every deploy, health-gates the rollout, and auto-rolls-back on failure.
# Rollback to any previously deployed version is a seconds-long image swap.
#
#   ./33pol-deploy.sh deploy                 # build + snapshot + deploy + verify
#   ./33pol-deploy.sh rollback               # instant swap to previous version
#   ./33pol-deploy.sh rollback --to <ver>    # swap to a specific version
#   ./33pol-deploy.sh status                 # current/previous version + health
#   ./33pol-deploy.sh versions               # locally built image versions
#   ./33pol-deploy.sh history                # deploy/rollback audit log
#   ./33pol-deploy.sh backup                 # database snapshot now
#   ./33pol-deploy.sh restore <file>         # restore database from snapshot
#   ./33pol-deploy.sh list-backups
#   ./33pol-deploy.sh logs [service]
#   ./33pol-deploy.sh prune [--keep N]       # trim old images + backups
#
# Run  ./33pol-deploy.sh help  for the full flag list.
# =============================================================================
set -Eeuo pipefail

# --- Locations --------------------------------------------------------------
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"
ENV_FILE="${SCRIPT_DIR}/.env"
STATE_DIR="${SCRIPT_DIR}/.deploy"
OVERRIDE_FILE="${STATE_DIR}/compose.image.yml"
STATE_FILE="${STATE_DIR}/state.env"
HISTORY_FILE="${STATE_DIR}/history.log"
BACKUP_DIR="${STATE_DIR}/backups"

IMAGE_REPO="33pol-gateway"        # versioned tags live under this repository
GATEWAY_SERVICE="gateway"
DB_SERVICE="postgres"

# --- Defaults (override via flags) ------------------------------------------
VERSION=""
PROFILES=""
DO_BACKUP=true
HEALTH_GATE=true
HEALTH_TIMEOUT=120
KEEP=5
ASSUME_YES=false
DRY_RUN=false
ROLLBACK_TO=""
RESTORE_DB_FILE=""

# --- Pretty logging ---------------------------------------------------------
if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'; C_DIM=$'\033[2m'; C_RED=$'\033[31m'; C_GREEN=$'\033[32m'
  C_YELLOW=$'\033[33m'; C_BLUE=$'\033[34m'; C_BOLD=$'\033[1m'
else
  C_RESET=""; C_DIM=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_BLUE=""; C_BOLD=""
fi
# Diagnostics go to stderr so stdout stays clean for functions that return data
# via command substitution (e.g. backup_db prints the snapshot path).
log()   { printf '%s==>%s %s\n'  "${C_BLUE}"   "${C_RESET}" "$*" >&2; }
ok()    { printf '%s ✓ %s%s\n'   "${C_GREEN}"  "$*" "${C_RESET}" >&2; }
warn()  { printf '%s ! %s%s\n'   "${C_YELLOW}" "$*" "${C_RESET}" >&2; }
err()   { printf '%s ✗ %s%s\n'   "${C_RED}"    "$*" "${C_RESET}" >&2; }
die()   { err "$*"; exit 1; }
step()  { printf '\n%s%s%s\n' "${C_BOLD}" "$*" "${C_RESET}" >&2; }

trap 'err "Aborted at line ${LINENO}."' ERR

# --- Prerequisite + compose plumbing ----------------------------------------
require() { command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"; }

preflight() {
  require docker
  docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (docker compose ...)."
  [[ -f "${COMPOSE_FILE}" ]] || die "Compose file not found: ${COMPOSE_FILE}"
  [[ -f "${ENV_FILE}" ]] || die "Missing ${ENV_FILE}. Copy .env.example to .env and set the required secrets."
  mkdir -p "${STATE_DIR}" "${BACKUP_DIR}"
  ensure_override
}

# Static override that pins the gateway to a pre-built, version-tagged image.
# `docker compose up` then uses that exact image instead of rebuilding in place,
# which is what makes an instant rollback (swap the tag, `up -d`) possible.
ensure_override() {
  cat >"${OVERRIDE_FILE}" <<'YAML'
# Auto-generated by 33pol-deploy.sh — do not edit.
# Pins the gateway to a versioned, pre-built image tag (GATEWAY_IMAGE_TAG).
services:
  gateway:
    image: "33pol-gateway:${GATEWAY_IMAGE_TAG:-latest}"
YAML
}

# Build the `--profile` args from a comma list.
profile_args() {
  local out=() p
  if [[ -n "${PROFILES}" ]]; then
    IFS=',' read -ra _ps <<<"${PROFILES}"
    for p in "${_ps[@]}"; do [[ -n "${p}" ]] && out+=(--profile "${p}"); done
  fi
  printf '%s\n' "${out[@]:-}"
}

# Run docker compose with base + override, the resolved image tag, and profiles.
dc() {
  local tag="${1:?tag}"; shift
  mapfile -t _profiles < <(profile_args)
  if [[ "${DRY_RUN}" == true ]]; then
    printf '%s[dry-run]%s GATEWAY_IMAGE_TAG=%s docker compose ... %s\n' \
      "${C_DIM}" "${C_RESET}" "${tag}" "$*" >&2
    return 0
  fi
  GATEWAY_IMAGE_TAG="${tag}" docker compose \
    --env-file "${ENV_FILE}" \
    -f "${COMPOSE_FILE}" -f "${OVERRIDE_FILE}" \
    "${_profiles[@]}" "$@"
}

# --- State helpers ----------------------------------------------------------
state_get() { [[ -f "${STATE_FILE}" ]] && (grep -E "^$1=" "${STATE_FILE}" | tail -1 | cut -d= -f2-) || true; }

state_set() {
  local key="$1" val="$2" tmp
  mkdir -p "${STATE_DIR}"; touch "${STATE_FILE}"
  tmp="$(mktemp)"
  grep -vE "^${key}=" "${STATE_FILE}" >"${tmp}" 2>/dev/null || true
  printf '%s=%s\n' "${key}" "${val}" >>"${tmp}"
  mv "${tmp}" "${STATE_FILE}"
}

history_add() {
  mkdir -p "${STATE_DIR}"
  printf '%s | %-10s | %-28s | %s\n' \
    "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$1" "$2" "$3" >>"${HISTORY_FILE}"
}

# Read a non-secret value from .env (safe: exact key match, no shell sourcing).
env_get() { grep -E "^$1=" "${ENV_FILE}" 2>/dev/null | tail -1 | cut -d= -f2- || true; }

# --- Version computation ----------------------------------------------------
compute_version() {
  [[ -n "${VERSION}" ]] && { printf '%s' "${VERSION}"; return; }
  local sha stamp dirty=""
  if git -C "${SCRIPT_DIR}" rev-parse --git-dir >/dev/null 2>&1; then
    sha="$(git -C "${SCRIPT_DIR}" rev-parse --short=10 HEAD 2>/dev/null || echo nogit)"
    git -C "${SCRIPT_DIR}" diff --quiet 2>/dev/null || dirty="-dirty"
  else
    sha="nogit"
  fi
  stamp="$(date -u '+%Y%m%d%H%M%S')"
  printf '%s-%s%s' "${sha}" "${stamp}" "${dirty}"
}

image_exists() { docker image inspect "${IMAGE_REPO}:$1" >/dev/null 2>&1; }

confirm() {
  [[ "${ASSUME_YES}" == true ]] && return 0
  local reply
  printf '%s%s%s [y/N] ' "${C_YELLOW}" "$1" "${C_RESET}"
  read -r reply || true
  [[ "${reply}" =~ ^[Yy]$ ]]
}

# --- Database backup / restore ---------------------------------------------
db_running() { dc latest ps --status running "${DB_SERVICE}" 2>/dev/null | grep -q "${DB_SERVICE}"; }

backup_db() {
  local label="${1:-manual}" file
  file="${BACKUP_DIR}/db-${label}-$(date -u '+%Y%m%d%H%M%S').dump"
  if [[ "${DRY_RUN}" == true ]]; then log "[dry-run] would snapshot database -> ${file}"; printf '%s' "${file}"; return 0; fi
  if ! db_running; then warn "Database container is not running; skipping snapshot."; return 0; fi
  log "Snapshotting database -> $(basename "${file}")"
  # pg_dump runs inside the container using its own POSTGRES_* env — no secret handling on the host.
  dc latest exec -T "${DB_SERVICE}" sh -c \
    'pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Fc' >"${file}" \
    || { rm -f "${file}"; die "Database snapshot failed."; }
  ok "Snapshot saved: ${file} ($(du -h "${file}" | cut -f1))"
  printf '%s' "${file}"
}

restore_db() {
  local file="$1"
  [[ -f "${file}" ]] || die "Backup file not found: ${file}"
  db_running || die "Database container is not running; start the stack before restoring."
  warn "This OVERWRITES the current database with ${file}."
  confirm "Proceed with database restore?" || die "Restore cancelled."
  log "Restoring database from $(basename "${file}") ..."
  dc latest exec -T "${DB_SERVICE}" sh -c \
    'pg_restore -U "$POSTGRES_USER" -d "$POSTGRES_DB" --clean --if-exists --no-owner' <"${file}" \
    || die "Database restore reported errors."
  ok "Database restored."
}

# --- Health gate ------------------------------------------------------------
http_ok() { # $1 url -> returns 0 if HTTP 200
  local url="$1"
  if command -v curl >/dev/null 2>&1; then
    curl -fsS -o /dev/null --max-time 4 "${url}" 2>/dev/null
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O /dev/null -T 4 "${url}" 2>/dev/null
  else
    local host port; host="${url#http://}"; host="${host%%/*}"
    port="${host##*:}"; host="${host%%:*}"
    exec 9<>"/dev/tcp/${host}/${port}" 2>/dev/null || return 1
    printf 'GET /health/live HTTP/1.1\r\nHost: %s\r\nConnection: close\r\n\r\n' "${host}" >&9
    local line; read -r line <&9; exec 9<&- 9>&-
    [[ "${line}" == *" 200 "* ]]
  fi
}

wait_healthy() {
  local port url waited=0
  port="$(env_get GATEWAY_PORT)"; port="${port:-8080}"
  url="http://127.0.0.1:${port}/health/live"
  [[ "${DRY_RUN}" == true ]] && { log "[dry-run] would health-gate ${url}"; return 0; }
  log "Waiting for gateway health (${url}, timeout ${HEALTH_TIMEOUT}s) ..."
  while (( waited < HEALTH_TIMEOUT )); do
    if http_ok "${url}"; then ok "Gateway is live."; return 0; fi
    sleep 3; waited=$((waited + 3))
    printf '%s   ... %ss%s\r' "${C_DIM}" "${waited}" "${C_RESET}"
  done
  printf '\n'; return 1
}

# --- Commands ---------------------------------------------------------------
cmd_deploy() {
  preflight
  local new_version prev_version backup_file=""
  new_version="$(compute_version)"
  prev_version="$(state_get CURRENT_VERSION)"

  step "Deploying 33pol gateway"
  printf '  version:  %s%s%s\n' "${C_BOLD}" "${new_version}" "${C_RESET}"
  printf '  previous: %s\n' "${prev_version:-<none>}"
  [[ -n "${PROFILES}" ]] && printf '  profiles: %s\n' "${PROFILES}"
  confirm "Continue?" || die "Deploy cancelled."

  # 1) Snapshot the database first — this is the real rollback insurance because
  #    EF Core migrations auto-apply on startup and are not auto-reverted.
  if [[ "${DO_BACKUP}" == true ]]; then
    step "1/4 Database snapshot"
    backup_file="$(backup_db "predeploy-${new_version}")"
  else
    warn "Skipping database snapshot (--no-backup); rollback will be image-only."
  fi

  # 2) Build the immutable, version-tagged image.
  step "2/4 Build image ${IMAGE_REPO}:${new_version}"
  dc "${new_version}" build "${GATEWAY_SERVICE}"
  ok "Image built."

  # 3) Roll out (postgres stays up; only gateway is recreated onto the new image).
  step "3/4 Roll out"
  dc "${new_version}" up -d --remove-orphans
  state_set PREVIOUS_VERSION "${prev_version}"
  state_set CURRENT_VERSION "${new_version}"

  # 4) Health-gate; auto-rollback on failure.
  step "4/4 Verify"
  if [[ "${HEALTH_GATE}" == true ]] && ! wait_healthy; then
    err "Gateway did not become healthy — auto-rolling back."
    history_add DEPLOY "${new_version}" "FAILED — auto-rollback"
    if [[ -n "${prev_version}" ]] && image_exists "${prev_version}"; then
      rollback_to "${prev_version}" "auto"
    else
      err "No previous image to roll back to. Inspect logs:  $0 logs ${GATEWAY_SERVICE}"
    fi
    if [[ -n "${backup_file}" ]]; then
      warn "If the failed release changed the schema, restore the pre-deploy database:"
      printf '     %s restore %s\n' "$0" "${backup_file}"
    fi
    die "Deploy failed and was rolled back."
  fi

  history_add DEPLOY "${new_version}" "OK (prev ${prev_version:-none})"
  ok "Deployed ${new_version} successfully."
  prune_images_quiet
}

rollback_to() {
  local target="$1" reason="${2:-manual}"
  image_exists "${target}" || die "Image ${IMAGE_REPO}:${target} not found. Run '$0 versions' to list options."
  local current; current="$(state_get CURRENT_VERSION)"
  step "Rolling back gateway -> ${target}  (${reason})"
  dc "${target}" up -d --no-build --force-recreate "${GATEWAY_SERVICE}"
  state_set PREVIOUS_VERSION "${current}"
  state_set CURRENT_VERSION "${target}"
  if [[ "${HEALTH_GATE}" == true ]] && ! wait_healthy; then
    history_add ROLLBACK "${target}" "UNHEALTHY after rollback (${reason})"
    die "Rolled back to ${target} but it is not healthy — inspect:  $0 logs ${GATEWAY_SERVICE}"
  fi
  history_add ROLLBACK "${target}" "OK (${reason}, from ${current:-none})"
  ok "Now running ${target}."
}

cmd_rollback() {
  preflight
  local target="${ROLLBACK_TO}"
  [[ -z "${target}" ]] && target="$(state_get PREVIOUS_VERSION)"
  [[ -n "${target}" ]] || die "No previous version recorded. Specify one:  $0 rollback --to <version>   (see '$0 versions')"
  confirm "Roll back to ${target}?" || die "Rollback cancelled."
  [[ -n "${RESTORE_DB_FILE}" ]] && restore_db "${RESTORE_DB_FILE}"
  rollback_to "${target}" "manual"
}

cmd_status() {
  preflight
  local cur prev port
  cur="$(state_get CURRENT_VERSION)"; prev="$(state_get PREVIOUS_VERSION)"
  port="$(env_get GATEWAY_PORT)"; port="${port:-8080}"
  step "33pol deployment status"
  printf '  current version : %s%s%s\n' "${C_BOLD}" "${cur:-<unknown>}" "${C_RESET}"
  printf '  previous version: %s\n' "${prev:-<none>}"
  printf '  gateway port    : %s\n\n' "${port}"
  dc "${cur:-latest}" ps || true
  printf '\n'
  if http_ok "http://127.0.0.1:${port}/health/live"; then ok "Health: live"; else warn "Health: not responding on :${port}"; fi
}

cmd_versions() {
  preflight
  step "Locally built ${IMAGE_REPO} images (newest first)"
  local cur; cur="$(state_get CURRENT_VERSION)"
  docker image ls "${IMAGE_REPO}" --format '{{.Tag}}\t{{.CreatedSince}}\t{{.Size}}' \
    | grep -v '^latest' | sort -r \
    | while IFS=$'\t' read -r tag created size; do
        local marker="  "; [[ "${tag}" == "${cur}" ]] && marker="${C_GREEN}=>${C_RESET}"
        printf '%s %-30s %s%-16s%s %s\n' "${marker}" "${tag}" "${C_DIM}" "${created}" "${C_RESET}" "${size}"
      done
}

cmd_history() {
  preflight
  [[ -f "${HISTORY_FILE}" ]] || { warn "No deploy history yet."; return 0; }
  step "Deploy / rollback history"
  printf '%-20s | %-10s | %-28s | %s\n' "TIMESTAMP (UTC)" "ACTION" "VERSION" "RESULT"
  cat "${HISTORY_FILE}"
}

cmd_backup()  { preflight; backup_db "manual" >/dev/null; }
cmd_restore() { preflight; [[ -n "${1:-}" ]] || die "Usage: $0 restore <backup-file>"; restore_db "$1"; }

cmd_list_backups() {
  preflight
  step "Database snapshots in ${BACKUP_DIR}"
  if compgen -G "${BACKUP_DIR}/*.dump" >/dev/null; then
    ls -1t "${BACKUP_DIR}"/*.dump | while read -r f; do
      printf '  %-55s %s%s%s\n' "$(basename "${f}")" "${C_DIM}" "$(du -h "${f}" | cut -f1)" "${C_RESET}"
    done
  else
    warn "No snapshots found."
  fi
}

cmd_logs() { preflight; dc "$(state_get CURRENT_VERSION || echo latest)" logs -f --tail 200 "${1:-}"; }

prune_images_quiet() { KEEP="${KEEP}" prune_images >/dev/null 2>&1 || true; }
prune_images() {
  local cur prev keep_tags all removed=0
  cur="$(state_get CURRENT_VERSION)"; prev="$(state_get PREVIOUS_VERSION)"
  mapfile -t all < <(docker image ls "${IMAGE_REPO}" --format '{{.Tag}}' | grep -v '^latest' | sort -r)
  local kept=0
  for tag in "${all[@]}"; do
    # Always keep the current and previous versions regardless of position.
    if [[ "${tag}" == "${cur}" || "${tag}" == "${prev}" ]]; then continue; fi
    kept=$((kept + 1))
    if (( kept > KEEP )); then
      docker image rm "${IMAGE_REPO}:${tag}" >/dev/null 2>&1 && removed=$((removed + 1)) || true
    fi
  done
  (( removed > 0 )) && log "Pruned ${removed} old image(s)."
  return 0
}

cmd_prune() {
  preflight
  step "Pruning old images (keeping ${KEEP} most recent + current/previous) and backups"
  prune_images
  # Keep the newest KEEP backups.
  if compgen -G "${BACKUP_DIR}/*.dump" >/dev/null; then
    local n=0
    ls -1t "${BACKUP_DIR}"/*.dump | while read -r f; do
      n=$((n + 1)); (( n > KEEP )) && { rm -f "${f}"; log "Removed old backup $(basename "${f}")"; }
    done
  fi
  ok "Prune complete."
}

usage() {
  cat <<EOF
${C_BOLD}33pol-deploy.sh${C_RESET} — versioned Docker Compose deploy & instant rollback

${C_BOLD}COMMANDS${C_RESET}
  deploy                 Snapshot DB, build a version-tagged image, roll out,
                         health-gate, and auto-rollback if it doesn't come up.
  rollback               Instantly switch to the previous version (image swap).
  status                 Show current/previous version, container state, health.
  versions               List locally built gateway image versions.
  history                Show the deploy/rollback audit log.
  backup                 Take a database snapshot now.
  restore <file>         Restore the database from a snapshot.
  list-backups           List database snapshots.
  logs [service]         Follow logs (default: all services).
  prune                  Remove old image versions and backups.
  help                   This help.

${C_BOLD}FLAGS${C_RESET}
  --version <v>          Explicit image version (default: <git-sha>-<utc>).
  --to <v>               Rollback target version (default: previous).
  --profiles <a,b>       Compose profiles: mock, observability, full.
  --restore-db <file>    Also restore this DB snapshot during rollback.
  --timeout <sec>        Health-gate timeout (default: ${HEALTH_TIMEOUT}).
  --keep <n>             Versions/backups to keep on prune (default: ${KEEP}).
  --no-backup            Skip the pre-deploy database snapshot.
  --no-health-gate       Don't wait for health / don't auto-rollback.
  --yes, -y              Don't prompt for confirmation.
  --dry-run              Print actions without executing.

${C_BOLD}EXAMPLES${C_RESET}
  ./33pol-deploy.sh deploy --profiles observability --yes
  ./33pol-deploy.sh deploy --version v2.1.0
  ./33pol-deploy.sh rollback                       # to previous version
  ./33pol-deploy.sh rollback --to a1b2c3d4-2026... --restore-db .deploy/backups/db-...dump
  ./33pol-deploy.sh status
EOF
}

# --- Arg parsing ------------------------------------------------------------
COMMAND="${1:-help}"; shift || true
POSITIONAL=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)      VERSION="${2:?}"; shift 2 ;;
    --to)           ROLLBACK_TO="${2:?}"; shift 2 ;;
    --profiles)     PROFILES="${2:?}"; shift 2 ;;
    --restore-db)   RESTORE_DB_FILE="${2:?}"; shift 2 ;;
    --timeout)      HEALTH_TIMEOUT="${2:?}"; shift 2 ;;
    --keep)         KEEP="${2:?}"; shift 2 ;;
    --no-backup)    DO_BACKUP=false; shift ;;
    --no-health-gate) HEALTH_GATE=false; shift ;;
    -y|--yes)       ASSUME_YES=true; shift ;;
    --dry-run)      DRY_RUN=true; shift ;;
    -h|--help)      COMMAND="help"; shift ;;
    --) shift; while [[ $# -gt 0 ]]; do POSITIONAL+=("$1"); shift; done ;;
    -*) die "Unknown flag: $1  (see '$0 help')" ;;
    *)  POSITIONAL+=("$1"); shift ;;
  esac
done

case "${COMMAND}" in
  deploy)        cmd_deploy ;;
  rollback)      cmd_rollback ;;
  status)        cmd_status ;;
  versions)      cmd_versions ;;
  history)       cmd_history ;;
  backup)        cmd_backup ;;
  restore)       cmd_restore "${POSITIONAL[0]:-}" ;;
  list-backups)  cmd_list_backups ;;
  logs)          cmd_logs "${POSITIONAL[0]:-}" ;;
  prune)         cmd_prune ;;
  help|"")       usage ;;
  *)             err "Unknown command: ${COMMAND}"; usage; exit 1 ;;
esac
