<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\33pol.Api\33pol.Api.csproj" />
    <ProjectReference Include="..\..\src\33pol.Core\33pol.Core.csproj" />
  </ItemGroup>
</Project>
