// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pol33.Persistence;

#nullable disable

namespace Pol33.Persistence.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260716102150_DashboardStatsPersistence")]
    partial class DashboardStatsPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pol33.Persistence.Entities.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assignee")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix");

                    b.HasIndex("TenantId");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.ApiKeyModelGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ModelPattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId", "ModelPattern")
                        .IsUnique();

                    b.ToTable("api_key_model_grants", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.BillingEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<long>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("InputCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("OutputCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<long>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("ApiKeyId", "RecordedAt");

                    b.HasIndex("CostCenter", "RecordedAt");

                    b.HasIndex("TenantId", "RecordedAt");

                    b.ToTable("billing_events", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.BudgetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountLimit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("HardStopEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PeriodStartDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("WarningThresholdRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.DailyUsageRollupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UsageDate", "TenantId", "ModelId", "CostCenter")
                        .IsUnique();

                    b.ToTable("daily_usage_rollups", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.GatewayStatsSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorsPerModelJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("QuotaRejections")
                        .HasColumnType("bigint");

                    b.Property<long>("RateLimitRejections")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestsPerModelJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("TotalErrors")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRequests")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("gateway_stats_snapshot", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.ModelGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ModelPattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ModelPattern");

                    b.ToTable("model_grants", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.PlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConcurrencyLimit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("MonthlyTokenLimit")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RateCardSlug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("RequestsPerMinute")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.QuotaAllocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<long>("RequestLimit")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SoftLimitRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("TokenLimit")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodStart", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("quota_allocations", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.QuotaUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UsedRequests")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedTokens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodStart")
                        .IsUnique();

                    b.ToTable("quota_usages", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.QuotaUsageSnapshotEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<long>("Used")
                        .HasColumnType("bigint");

                    b.HasKey("PartitionKey");

                    b.ToTable("quota_usage_snapshots", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.RateCardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("InputPricePerMillionTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("OutputPricePerMillionTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ModelId", "EffectiveFrom");

                    b.ToTable("rate_cards", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.RecentRequestSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsStreaming")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ModelId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("recent_requests", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PlanSlug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.ApiKeyEntity", b =>
                {
                    b.HasOne("Pol33.Persistence.Entities.TenantEntity", "Tenant")
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.ApiKeyModelGrantEntity", b =>
                {
                    b.HasOne("Pol33.Persistence.Entities.ApiKeyEntity", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.BudgetEntity", b =>
                {
                    b.HasOne("Pol33.Persistence.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.ModelGrantEntity", b =>
                {
                    b.HasOne("Pol33.Persistence.Entities.TenantEntity", "Tenant")
                        .WithMany("ModelGrants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Pol33.Persistence.Entities.TenantEntity", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("ModelGrants");
                });
#pragma warning restore 612, 618
        }
    }
}
