<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\33pol.Core\33pol.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\33pol.Core.Tests\TestData\error-*.golden.json" Link="TestData\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
